config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "splash#index"

  resources :categories, only: [:index, :new, :create,:destroy] do
    resources :transactions, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :related_transactions, class_name: 'Transaction'

  validates :name, :icon, presence: true

  def total_amount_of_transactions
    related_transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :related_transactions, class_name: 'Transaction'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :back_path

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def back_path
    case "#{controller_name}/#{action_name}"
    when 'categories/index' || 'transactions/index' || 'categories/new'
      categories_path
    when 'transactions/new'
      category_transactions_path
    else
      root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories = current_user.categories.includes(:related_transactions).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
# app/controllers/splash_controller.rb

class SplashController < ApplicationController
  before_action :redirect_based_on_authentication

  def index; end

  private

  def redirect_based_on_authentication
    return unless user_signed_in?

    redirect_to categories_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = current_user.categories.find(params[:category_id])

    @transactions = @category.related_transactions.order(created_at: :desc)
  end

  def new
    @category = Category.find(params[:category_id])
    @categories = current_user.categories.all
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.related_transactions.build(transaction_params)
    category_id = params.dig(:transaction, :category_id)
    @transaction.category_ids = category_id if category_id.present?
    if @transaction.save
      @category = Category.find(category_id) if category_id.present?
      redirect_to category_transactions_path(@category)
    else
      render :new
    end
  end

  def destroy; end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="h-full flex flex-col justify-between w-full">
  <div>
    <% if @categories.any? %>
      <% @categories.each do |category| %>
        <%= link_to category_transactions_path(category) do %>
          <div class="bg-white rounded-md shadow-md h-32 flex m-2 p-2 items-center">
            <figure class="w-24 mr-4"><img src="<%= category.icon %>"/></figure>
            <div class="w-full flex justify-between px-2">
              <span class="text-lg text-custom-normal"><%= category.name %></span>
              <span class="text-custom-bold font-bold"><%= number_to_currency(category.total_amount_of_transactions) %></span>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="text-custom-normal p-4 text-center">No categories available.</p>
    <% end %>
  </div>

  <div class="bg-custom-green px-2 py-3 text-center border-2 border-white">
    <div class="border bg-custom-green text-white uppercase px-2 py-2">
      <%= link_to 'Add new category', new_category_path, class: 'text-white' %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= form_with(model: @category, url: categories_path, method: :post, class: 'h-full flex flex-col container') do |form| %>
  <div class="container bg-white flex flex-col items-center">
  <%= form.text_field :name, placeholder: 'Name', class: 'container border-none pl-4' %>
  <hr class="w-11/12"/>
  <%= form.text_field :icon, placeholder: 'Icon', class: 'container border-none pl-4' %>
  </div>

  <div class="bg-custom-green px-2 py-3 text-center border-2 border-white mt-auto">
    <div class="border bg-custom-green text-white uppercase px-2 py-2">
      <%= form.submit 'Save', class: 'text-white' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col h-screen bg-gray-100">
  <%= render 'shared/navbar' %>
    <main class="container mx-auto flex flex-col flex-1">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="h-16 flex items-center justify-between bg-custom-blue p-4">
    <% unless controller_name == 'categories' && action_name == 'index' %>
    <%= link_to "<", back_path, class: "text-white text-2xl" %>
    <% end %>
    <span class="text-white text-xl font-semibold">
      <% if controller_name == 'categories' && action_name == 'index' %>
        Home
      <% elsif controller_name == 'transactions' && action_name == 'index' %>
        Transactions
      <% elsif controller_name == 'categories' && action_name == 'new' %>
        Add New Category
      <% elsif controller_name == 'transactions' && action_name == 'new' %>
        Add New Transaction
      <% else %>
        Budget Manager
      <% end %>
    </span>

    <div class="space-x-4">
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "text-white" %>
    </div>
  </nav>
<% else %>
  <% if controller_name == 'splash' && action_name == 'index' %>
  <% elsif controller_name == 'sessions' && action_name == 'new' %>
    <nav class="h-16 flex items-center justify-between bg-custom-blue p-4">
      <%= link_to "<", back_path, class: "text-white text-4xl" %>
      <span class="text-white text-xl font-semibold uppercase">Login</span>
      <%= link_to "Log in", "#", class: "text-white", onclick: "document.getElementById('loginForm').submit(); return false;" %>
    </nav>
  <% elsif controller_name == 'registrations' && action_name == 'new' %>
    <nav class="h-16 flex items-center justify-between bg-custom-blue p-4">
      <%= link_to "<", back_path, class: "text-white text-4xl" %>
      <span class="text-white text-xl font-semibold uppercase">Register</span>
      <%= link_to "Next", "#", class: "text-white", onclick: "document.getElementById('registrationForm').submit(); return false;" %>
    </nav>
  <% end %>
<% end %>

app/views/splash/index.html.erb
<div class="min-h-screen flex flex-col justify-between items-center max-w-screen">
  <h1 class="text-3xl text-custom-bold my-auto">BUDGET MANAGER</h1>
  <div class="w-full flex flex-col space-y-2">
      <%= link_to 'LOG IN', new_user_session_path, class: 'w-full bg-custom-blue text-xl font-bold text-white py-6 px-4 rounded text-center' %>
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'w-full text-custom-normal text-xl font-bold hover:underline py-6 px-4 rounded text-center' %>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="flex flex-col justify-between h-full">

  <% if @transactions.exists? %>
    <div class="flex flex-col">
    <% @transactions.each do |transaction| %>
      <div class="flex bg-white rounded-md shadow-md p-4 m-2 justify-between">
        <span class="text-lg text-custom-normal mb-2"><%= transaction.name %></span>
        <span class="text-custom-bold font-bold"><%= number_to_currency(transaction.amount) %></span>
      </div>
    <% end %>
    </div>
  <% else %>
    <p class="text-custom-normal p-4 text-center">No transactions</p>
  <% end %>

  <div class="bg-custom-green px-2 py-3 text-center border-2 border-white">
    <div class="border bg-custom-green text-white uppercase px-2 py-2">
      <%= link_to 'Add new transaction', new_category_transaction_path, class: 'text-white' %>
    </div>
  </div>

</div>

app/views/transactions/new.html.erb
 <%= form_with(model: [Transaction.new], url: category_transactions_path(@category), method: :post, class: 'h-full flex flex-col container') do |form| %>
    <div class="container bg-white flex flex-col items-center">
      <%= form.text_field :name, placeholder: 'Name',class: 'container border-none pl-4' %>
      <hr class="w-11/12"/>
      <%= form.text_field :amount, placeholder: 'Amount',class: 'container border-none pl-4' %>
      <hr class="w-11/12"/>
      <%= select_tag "transaction[category_id]", options_for_select(@categories.map { |category| [category.name, category.id] }), { prompt: "Select Category", required: true, class: "self-start border-none form-select text-custom-normal pl-4"} %>
    </div>

    <div class="bg-custom-green px-2 py-3 text-center border-2 border-white mt-auto">
      <div class="border bg-custom-green text-white uppercase px-2 py-2">
        <%= form.submit 'Save', class: 'text-white' %>
      </div>
    </div>
  <% end %>